service: team-1-etl

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  
  region: eu-west-1
  
  iam:  
    role:
      permissionsBoundary: arn:aws:iam::883232869702:policy/ScopePermissions

package:
  include: 
    - src/**
    - handler.py
  exclude:
    - "*"
    - "*/**" 
  individually: true
  excludeDevDependencies: false

functions:
  etl:
    handler: handler.handel
    timeout: 300
    layers:
      - !Ref PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    layer: true
    dockerizePip: true